### ISSUE TITLE
Is `setopt extended_glob` required?

### ISSUE THREAD

**Issue by DerRockWolf** [mattmc3/antidote#177]
Hi, first up thanks for creating antidote :slightly_smiling_face: 

I don't want `extended_glob` to be enabled in zsh.
After looking what enabled `extended_glob` in my setup I found this line in `antidote load`:
https://github.com/mattmc3/antidote/blob/90deef194d38206a0de63980b6147c3a83850055/functions/antidote-load#L8

If I add `unsetopt extended_glob` after `antidote load` everything still seems to function as far as I can see.
Are there any problems with disabling `extended_glob` after calling `antidote load`?

**Comment by mattmc3** [comment]
Thanks for the kind words. You got it right - you can run `setopt NO_extended_glob` or `unsetopt extended_glob` right after `antidote load`. There's no problem disabling it as far as antidote is concerned. As long as you don't use a plugin that expects `extended_glob`, and then you just unset it. Although in that case you could open an issue with the plugin maintainer because if a plugin requires it, `setopt local_options extended_glob` is the right way to go about it.

**Comment by mattmc3** [comment]
I cut a new release so that you don't need to do anything once you upgrade to v1.9.6.

**Comment by DerRockWolf** [comment]
Wow, thanks for looking after it that quickly :heart:
