### ISSUE TITLE
git completions don't work even though zsh-completions is enabled

### ISSUE THREAD

**Issue by marcinjahn** [mattmc3/antidote#23]
I ahve the following plugins:

```
zsh-users/zsh-completions
zsh-users/zsh-autosuggestions
lukechilds/zsh-nvm
# autojump
zsh-users/zsh-syntax-highlighting
dikiaap/dotfiles path:.oh-my-zsh/themes/oxide.zsh-theme
# ohmyzsh/ohmyzsh path:plugins/gitfast
```

Somehow `git` commands are not being autrocompleted when i press TAB. Why is that?

**Comment by mattmc3** [comment]
This doesn't sound like an issue with antidote, but rather something to do with your specific config. One thing I'd suggest is that plugin order matters - certain plugins like zsh-syntax-highlighting need to be sourced at the end of your plugins file (https://github.com/zsh-users/zsh-syntax-highlighting#faq), but if you include some of the other zsh-users plugins, those have other ordering rules (https://github.com/zsh-users/zsh-history-substring-search#usage). It can get pretty confusing and it's unfortunate that the docs aren't cohesive across all zsh-users repos.

My first suggestion would be to try re-arranging your plugins file to this order and see if that resolves your issue:

```
# non-zsh-users plugins first
lukechilds/zsh-nvm
dikiaap/dotfiles path:.oh-my-zsh/themes/oxide.zsh-theme

# zsh-users plugins last
zsh-users/zsh-completions
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
```

Secondly, you need to make sure somewhere in your config you are running `compinit`, and that git completions are available to Zsh. If you're on a Mac, there's some discussion of this issue here: https://stackoverflow.com/questions/24513873/git-tab-completion-not-working-in-zsh-on-mac

Thirdly, might I humbly suggest you could choose to try to resolve this simply by using my Zephyr plugin. Add this to your plugins file:

```
mattmc3/zephyr path:plugins/completions
```

Good luck. Closing as a non-antidote issue.

**Comment by marcinjahn** [comment]
Thanks @mattmc3, zephyr is all I needed. You did an amazing job with zsh tooling, I use antidote on all my PCs.

**Comment by mattmc3** [comment]
Thanks for the kind words @marcinjahn. I'm so glad this resolved your issue.

**Comment by mattmc3** [comment]
For future reference, additional documentation about completions is now available here: https://getantidote.github.io/completions

**Comment by marcinjahn** [comment]
Cool, that definitely makes things easier for new users, especially if they don’t really understand how it all works (like me :P)
