### ISSUE TITLE
Why choose local over remote?

### ISSUE THREAD

**Issue by mrienstra** [mattmc3/antidote#84]
Hi!

Looking at https://github.com/mattmc3/zdotdir/blob/main/.zplugins, I see lines like:
`$ZDOTDIR/plugins/fancy-ctrl-z`

Wondering why one would choose to do this, rather than:
`ohmyzsh/ohmyzsh path:plugins/fancy-ctrl-z`

Performance? Versioning?

I did a cursory search of the docs and didn't see this discussed, but I may have overlooked something. Is the answer worth adding to the docs?

**Comment by mattmc3** [comment]
If you trust Oh-My-Zsh to always work for you, or are willing to fix small breakages when they happen, then relying on remote is totally fine. If you are concerned that they’ll introduce a dependency on a variable or function from OMZ’s lib that you don’t know about, then making a local copy protects you from those kinds of breaking changes in the future. Personally, I don’t trust the lack of rigor in OMZ, so I’ll often copy what I want to my own config to lock it in, or find a dedicated project that forks OMZ plugins I like.

I tweak my personal config a lot (and change my mind a lot too), so I would rather not document my personal whims in antidote - this project is great because it’s agnostic to whichever method you’d rather use - local/remote plugins.

That said, if there’s verbiage that you think might help others and you want to contribute to the docs, I’d consider a PR.
